# Generated by Django 3.2.20 on 2023-09-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('numero_cupom', models.CharField(max_length=5, unique=True, verbose_name='Numero Cupom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
